### ISSUE TITLE
Checklist for v0.4.3

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/lvsfunc#115]
# v0.4.3 Checklist

These are all the things I want to finish before I push for a v0.4.3 release.
This list is not final, and things may be added at any point.

## General

- [x] #120

## Write/update

- [x] Double-check all default values, use sane defaults that give the best generic solution
- [x] Rename `ivtc_credits` to `pulldown_credits` (will remain as alias to give people time to update)
- [x] Fix incorrect option being picked by pick_remograin/repair ([convo][sam_pick])
- [x] #130 (@Setsugennoao)

## Deprecate

- [x] #111

## Support

I'd like feature requests or updates to be added to this issue if there's no other relevant issue already. What would you like to see in v0.4.3?

To be updated.

[sam_pick]: https://discord.com/channels/856381934052704266/856383302097043497/982976043004592149
