### ISSUE TITLE
diff: Improvements checklist

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/lvsfunc#65]
Some things I think can be done to improve ``lvsfunc.comparison.diff`` after hearing some user feedback:

- [x] Return ranges when possible instead of just single frames with `return_frames=True`
- [x] ~~Some kind of output file if specified that can be referenced later (and ideally will not get overwritten) ~~Was handled in #40, and there it was determined it'd be better to just return the frames (which it does right now).
- [x] ~~Param to create a bookmark file, or to add to an existing bookmark file maybe?~~ Likewise, by outputting the list of frame ranges, the user can write this themselves.
- [x] ~~If vspreview/vsedit at one point allows for it, maybe somehow overwrite the frame number you can jump to to only display the frame numbers of the actual frames taken (instead of going sequentially from 0-1000 for example like it would normally). This would make copy-pasting values a lot easier.~~ Unlikely to ever happen, so just marking this as done.

These aren't hard requirements, but potential improvements to be made at a later date.

**Comment by LightArrowsEXE** [comment]
Return ranges and exclusion ranges from #78 and #66

**Comment by LightArrowsEXE** [comment]
Comments added to the remaining 3 tasks about their viability, as well as has and hasn't been discussed so far. No real reason to keep this issue open any longer.
