### ISSUE TITLE
Checklist for v0.4.0

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/lvsfunc#75]
These are all the things I want to finish before I push for a v0.4.0 release.
This list is not final, and things may be added at any point.

General:

- [x] Resolve all currently open PRs and issues (#60, #65, #66, #70, #74) 
- [x] Update all functions to use 3.10 annotations and typehints
- [x] Update all functions to use relevant decorators wherever possible
- [x] ~~Update all AVS ports ([request](https://github.com/Irrational-Encoding-Wizardry/lvsfunc/issues/74#issuecomment-1029035634))~~ This will be reserved for a future version.

Write/update the following functions:

- [x] #84
- [x] ~~Anime IVTC port (likely Kongarou's rewrite)~~ (Kogarou stalled 😠)
- [x] ~~shift_tint -> general detint function~~ (Potential Tweak rewrite instead in a later version?)
- [x] new detail mask
- [x] ~~update source~~ (Too complex for lvsfunc, might make a separate module at some point)
- [x] New unsharpening function

Deprecate the following functions:

- [x] dehalo.deemphasize
- [x] deinterlace.dir_deshimmer
- [x] deinterlace.dir_unsharp
- [x] scale.test_descale

To be updated.
